# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-12-11 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='qq_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='QQ昵称'),
        ),
    ]
