# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-12-11 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20191211_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultrecord',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User', verbose_name='跟进人'),
        ),
    ]
