# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-12-20 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_auto_20191220_1825'),
        ('app01', '0005_auto_20191212_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(to='rbac.Role'),
        ),
    ]
